### ISSUE TITLE
Replace package.json "version": "0.0.1" with mix.exs version

### ISSUE THREAD

**Issue by johannesE** [straw-hat-llc/phoenix_assets_webpack#2]
Any idea how I would approach this? Best practice?
Or do you replace both values every time you deploy your app?

**Comment by yordis** [comment]
@johannesE I would do it if you want. I don't see why not.

One question, I am guessing that you mean replace it with the `mix version` from the `phoenix web app`, right!?

Even that, I don't think that `package.json` is useful. Normally that application is not pulled and used it in some other app so

but but

if you want to publish the whole app to `npm` for example and you want some deployment process that pull that app and deploy it, then it's important, and at that moment I wouldn't match it to some `mix` version because it's not the same from deployment prospective.

I could be doing required changes in some OTP app but that doesn't mean I need to upgrade the versioning of my frontend app.

**Comment by yordis** [comment]
Feel free to open it if you want to continue the discussion

**Comment by johannesE** [comment]
Sorry for my extremely late reply.
> One question, I am guessing that you mean replace it with the mix version from the phoenix web app, right!?

Yes, exactly.

>I could be doing required changes in some OTP app but that doesn't mean I need to upgrade the versioning of my frontend app.

You are right. And for that exact reason, we went one step further and completely took the client out of the phoenix app. Therefore I personally have no more reason to do that. Thank you for your help. :)
